import type { Metadata } from 'next'
import localFont from '@next/font/local'
import './globals.css'

const Epilogue = localFont({
  src: '../public/fonts/Epilogue-VariableFont_wght.ttf',
  variable: '--font-epilogue',
})

const Inter = localFont({
  src: '../public/fonts/Inter-VariableFont_slnt,wght.ttf',
  variable: '--font-inter',
})
const JetBrainsMono = localFont({
  src: '../public/fonts/JetBrainsMono-VariableFont_wght.ttf',
  variable: '--font-jetbrains-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={`${Epilogue.variable} ${Inter.variable} ${JetBrainsMono.variable}`}>
        {children}
      </body>
    </html>
  )
}
export default  RootLayout;